name: "Pull Request Docs Check"
on:
  # Triggers the workflow on push to the master branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip, install requirements
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools
          python3 -m pip install -U sphinx
          python3 -m pip install sphinx-rtd-theme
          cd docs/ 
          python3 -m pip install -r requirements.txt
          cd ..
          python3 -m pip install -i https://test.pypi.org/simple/ moniker
          sudo apt-get install pandoc

      - name: Make the docs
        run: |
          make -C docs/ clean
          make -C docs/ html
