name: "Pull Request Docs Check"
on:
  # Triggers the workflow on push to the master branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip, install requirements
        run: |
          # Upgrade pip
          python3 -m pip install --upgrade pip
          python3 -m pip install -U sphinx
          python3 -m pip install sphinx-rtd-theme
          cd docs/ 
          python3 -m pip install -r requirements.txt

      - name: Make the docs
        run: |
          make clean
          make html

      - name: Standup docs on gh-pages
        run: |
          cd docs/_build/html
          git init
          touch .nojekyll
          git add -A
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m "deploy"

      - name: Push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/_build/html
